server:
  port: 8080
spring:
  application:
    name: calling_external_api
  datasource:
    url: jdbc:h2:file:./db
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
valyuta-course: https://cbu:uz/uz/arkhiv-kursov-valyut/json